# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=20, verbose_name='标题')),
                ('a_content', models.TextField(verbose_name='内容')),
                ('a_create_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('a_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('abstract', models.CharField(blank=True, max_length=200, null=True, verbose_name='摘要')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
